### ISSUE TITLE
Fazer aparecer os mapas subidos na conta do A4A para o Urbigis Publico

### ISSUE THREAD

**Issue by ThierryAJean** [AddressForAll/in-BR#1]
Foi definido o padrão seguinte: urbigis.com/BR-SP-SaoJoseCampos.maps

**Comment by ThierryAJean** [comment]
Talvez isto seja outro problema, mas vou deixar nesta mesma issue: Os dados subidos no urbigis não são separados por município. O problema de visualização está bem explicado neste video: https://addressforall-my.sharepoint.com/personal/thierry_addressforall_org/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fthierry%5Faddressforall%5Forg%2FDocuments%2FParceiros%5F20%2FUrbimatica%5F20%2Fzoom%5F0%5FUrbigis%5FIgor%5F20210118%2Emp4&parent=%2Fpersonal%2Fthierry%5Faddressforall%5Forg%2FDocuments%2FParceiros%5F20%2FUrbimatica%5F20&originalPath=aHR0cHM6Ly9hZGRyZXNzZm9yYWxsLW15LnNoYXJlcG9pbnQuY29tLzp2Oi9nL3BlcnNvbmFsL3RoaWVycnlfYWRkcmVzc2ZvcmFsbF9vcmcvRVJ2LXJ6cVUwczlQa183QW55YXpvZWtCNmZTR05NZDNSVUFXVE5ONml5eDJ0UT9ydGltZT1uTWV3b3NTODJFZw

**Comment by ThierryAJean** [comment]
Ignacio nos respondeu e no falou que seria necessário entrar em cada conta de cada município e atribuir o mapa correspondente. 
O ideal seria subir estes dados e enviar um email para o município correspondente o usuário.

@IgorEliezer  vai redigir um email para que enviemos para o Ignácio.

**Comment by ThierryAJean** [comment]
Tivemos uma reunião com Ignacio e foram criados usuarios para cada municipio do Brasil. Ignacio nos mostrou como gerar Gojason para que estes possam ser colocados no osmlab de camadas de edição do OSM.

**Comment by ThierryAJean** [comment]
Igor vai subir dados de 2 ou 3 cidades para nos mostrar. BH e PoA por exemplo.

**Comment by ThierryAJean** [comment]
Tivemos uma reunião com Wille que nos recomendou criar um Wiki com a licença e reabrir um issue e encerrar a antiga: https://github.com/osmlab/editor-layer-index/pull/928 
Cremos que desta vez, vai andar.

**Comment by ThierryAJean** [comment]
Igor fechou a issue antiga e vai abrir uma nova. A licença foi salva na Wiki para facilitar aprovação da camada sugerida.

**Comment by IgorEliezer** [comment]
Fecho por não ser de aplicação vencida.
